apiVersion: v1
kind: Service
metadata:
  annotations:
    app: zookeeper
    kompose.service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
  namespace: default
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper
  type: NodePort
status:
  loadBalancer: {}
