apiVersion: v1
kind: Service
metadata:
  annotations:
    app: kafka
    kompose.service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
  namespace: default
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: kafka
  type: NodePort
status:
  loadBalancer: {}
