openapi: 3.0.0
paths:
  /hello/string:
    get:
      operationId: HelloController_getHelloStringRest
      summary: Get Hello String
      parameters: []
      responses:
        "200":
          description: Hello String
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HelloStringResponseDTO"
        "500":
          description: Internal Server Error
          content:
            application/json: {}
      tags: &a1
        - Hello
  /hello/json:
    get:
      operationId: HelloController_getHelloJsonRest
      summary: Get Hello JSON
      parameters: []
      responses:
        "200":
          description: Hello JSON
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloJsonResponseDTO"
        "500":
          description: Internal Server Error
          content:
            application/json: {}
      tags: *a1
  /websocket-client/send-messages:
    post:
      operationId: WebsocketClientController_sendMessage
      summary: Send Messages
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: Send Messages
        "500":
          description: Internal Server Error
          content:
            application/json: {}
      tags: &a2
        - websocket-client
  /websocket-client/send-events:
    post:
      operationId: WebsocketClientController_sendEvent
      summary: Send Events
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: Send Events
        "500":
          description: Internal Server Error
          content:
            application/json: {}
      tags: *a2
  /websocket-client/send-health:
    post:
      operationId: WebsocketClientController_sendHealth
      summary: Send Health
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        "200":
          description: Send Health
        "500":
          description: Internal Server Error
          content:
            application/json: {}
      tags: *a2
info:
  title: HTTPS API
  description: HTTPS API documentation
  version: "1.0"
  contact:
    name: name
    url: url
    email: email
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    HelloStringResponseDTO:
      type: object
      properties: {}
    DataDTO:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    HelloJsonResponseDTO:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/DataDTO"
